// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions, Firebase;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsRrTY223xNoOzCo89vavtFXfPxKYqmLw',
    appId: '1:670440352874:web:7370e8cf0f8b9dffa66e13',
    messagingSenderId: '670440352874',
    projectId: 'utmmart-13927',
    authDomain: 'utmmart-13927.firebaseapp.com',
    storageBucket: 'utmmart-13927.firebasestorage.app',
    measurementId: 'G-WSCC1Q27ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnLwP9G_6HUkjYKb597oCjaHVwbVkLXDw',
    appId: '1:670440352874:android:e20824688114d4bfa66e13',
    messagingSenderId: '670440352874',
    projectId: 'utmmart-13927',
    storageBucket: 'utmmart-13927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxSIBvm0Kk_RdRrUEMhLKbFlb5kCVJ5IY',
    appId: '1:670440352874:ios:d4dc9bd32ca48c64a66e13',
    messagingSenderId: '670440352874',
    projectId: 'utmmart-13927',
    storageBucket: 'utmmart-13927.firebasestorage.app',
    androidClientId: '670440352874-d8fmnv6ceoc7ouffeskdghbpcbancg99.apps.googleusercontent.com',
    iosClientId: '670440352874-2nb80s92rmnu1quvv0gj8qv11qqddkil.apps.googleusercontent.com',
    iosBundleId: 'com.example.utmmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxSIBvm0Kk_RdRrUEMhLKbFlb5kCVJ5IY',
    appId: '1:670440352874:ios:d4dc9bd32ca48c64a66e13',
    messagingSenderId: '670440352874',
    projectId: 'utmmart-13927',
    storageBucket: 'utmmart-13927.firebasestorage.app',
    androidClientId: '670440352874-d8fmnv6ceoc7ouffeskdghbpcbancg99.apps.googleusercontent.com',
    iosClientId: '670440352874-2nb80s92rmnu1quvv0gj8qv11qqddkil.apps.googleusercontent.com',
    iosBundleId: 'com.example.utmmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsRrTY223xNoOzCo89vavtFXfPxKYqmLw',
    appId: '1:670440352874:web:5f2e23ebea4738d1a66e13',
    messagingSenderId: '670440352874',
    projectId: 'utmmart-13927',
    authDomain: 'utmmart-13927.firebaseapp.com',
    storageBucket: 'utmmart-13927.firebasestorage.app',
    measurementId: 'G-H3X2JKQNNT',
  );

}